# Generated by Django 4.1.7 on 2023-02-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_image', models.ImageField(upload_to='')),
                ('job_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tab', models.CharField(max_length=100)),
                ('image_header', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('title_header', models.CharField(max_length=100)),
                ('skill_header', models.CharField(max_length=255)),
                ('about_me_title', models.TextField()),
                ('about_me_text', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('city_and_country', models.CharField(max_length=50)),
                ('facebook_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('behance_url', models.URLField()),
            ],
        ),
    ]
