# Generated by Django 4.1.7 on 2023-02-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='job_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='job_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='about_me_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='about_me_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='behance_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='city_and_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='image_header',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='skill_header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='title_header',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='title_tab',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
