# Generated by Django 4.1.7 on 2023-02-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_userdata_about_me_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image_header',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
