# Generated by Django 4.1.7 on 2023-02-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_userdata_image_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cv_file',
            field=models.FileField(null=True, upload_to='cv/'),
        ),
    ]
