# Generated by Django 4.1.7 on 2023-02-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_userdata_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='job_image',
            field=models.ImageField(blank=True, upload_to='portfolio-images/'),
        ),
    ]
